import { render, screen } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ requireOwner: vi.fn(), createClient: vi.fn(), getQontoIntegration: vi.fn(), isQontoConfigured: vi.fn(), syncQontoAction: vi.fn() }));
vi.mock("@/lib/auth/require-owner", () => ({ requireOwner:mocks.requireOwner }));
vi.mock("@/lib/supabase/server", () => ({ createClient:mocks.createClient }));
vi.mock("@/features/integrations/repository", () => ({ getQontoIntegration:mocks.getQontoIntegration }));
vi.mock("@/features/integrations/qonto-config", () => ({ isQontoConfigured:mocks.isQontoConfigured }));
vi.mock("@/features/integrations/actions", () => ({ syncQontoAction:mocks.syncQontoAction }));
import Page from "./page";
beforeEach(() => {vi.clearAllMocks(); mocks.requireOwner.mockResolvedValue({userId:"owner"}); mocks.createClient.mockResolvedValue({}); mocks.getQontoIntegration.mockResolvedValue(null); mocks.isQontoConfigured.mockReturnValue(false);});
it("renders owner-only Qonto and Tiime state", async () => {render(await Page()); expect(screen.getByRole("heading", {name:"Intégrations"})).toBeInTheDocument(); expect(mocks.getQontoIntegration).toHaveBeenCalledWith({},"owner"); expect(screen.getByText("Accès API à obtenir")).toBeInTheDocument();});
it("guards owner before reading integration data", async () => {mocks.requireOwner.mockRejectedValue(new Error("redirect")); await expect(Page()).rejects.toThrow("redirect"); expect(mocks.createClient).not.toHaveBeenCalled();});
