export const fakeAccount = {
  id: "account-fake",
  name: "Compte principal fictif",
  organization_id: "organization-fake",
  status: "active",
  main: true,
  iban: "FR7611111222233334444555566",
  bic: "FAKEFRPPXXX",
  currency: "EUR",
  balance: "1234.56",
  balance_cents: 123_456,
  authorized_balance: "1200.00",
  authorized_balance_cents: 120_000,
  updated_at: "2026-03-31T21:30:00.000Z",
  is_external_account: false,
  account_number: 1_234_567_890,
} as const;

export const fakeTransaction = {
  transaction_id: "transaction-fake",
  amount: 42.5,
  amount_cents: 4_250,
  settled_balance: 1277.06,
  settled_balance_cents: 127_706,
  attachment_ids: ["attachment-fake"],
  local_amount: 42.5,
  local_amount_cents: 4_250,
  side: "credit",
  operation_type: "transfer",
  currency: "EUR",
  local_currency: "EUR",
  label: "Virement fictif",
  settled_at: "2026-03-31T22:15:00.000Z",
  emitted_at: "2026-03-31T22:05:00.000Z",
  updated_at: "2026-03-31T22:30:00.000Z",
  status: "completed",
  note: "Donnée privée à éliminer",
  reference: null,
  vat_amount: null,
  vat_amount_cents: null,
  vat_rate: null,
  initiator_id: "initiator-fake",
  label_ids: ["label-fake"],
  attachment_lost: false,
  attachment_required: true,
  card_last_digits: "1234",
  card_id: "card-fake",
  category: "services",
  cashflow_category: { id: "category-fake", name: "Catégorie privée" },
  cashflow_subcategory: { id: "subcategory-fake", name: "Sous-catégorie privée" },
  id: "subject-fake",
  subject_type: "transfer",
  bank_account_id: "account-fake",
  transfer: {
    counterparty_account_number: "FR7612345678901234567890123",
    counterparty_account_number_format: "IBAN",
    counterparty_bank_identifier: "FAKEFRPPXXX",
    counterparty_bank_identifier_format: "SWIFT_BIC",
  },
} as const;

export const fakePendingTransaction = {
  ...fakeTransaction,
  transaction_id: "transaction-pending-fake",
  status: "pending",
  side: "debit",
  settled_at: null,
} as const;
