import {act, render, screen} from "@testing-library/react";
import {beforeEach, expect, it, vi} from "vitest";
const m=vi.hoisted(()=>({requireOwner:vi.fn(),createClient:vi.fn(),getQontoIntegration:vi.fn(),isQontoConfigured:vi.fn()}));
vi.mock("@/lib/auth/require-owner",()=>({requireOwner:m.requireOwner}));
vi.mock("@/lib/supabase/server",()=>({createClient:m.createClient}));
vi.mock("@/features/integrations/repository",()=>({getQontoIntegration:m.getQontoIntegration}));
vi.mock("@/features/integrations/qonto-config",()=>({isQontoConfigured:m.isQontoConfigured}));
vi.mock("next/navigation",()=>({usePathname:()=>"/dashboard",useRouter:()=>({refresh:vi.fn()})}));
vi.mock("@/features/integrations/auto-sync-action",()=>({autoSyncQontoAction:async()=>({status:"skipped"})}));
import Layout from "./layout";
beforeEach(()=>{vi.clearAllMocks();m.requireOwner.mockResolvedValue({userId:"owner"});m.createClient.mockResolvedValue({});m.isQontoConfigured.mockReturnValue(true);m.getQontoIntegration.mockResolvedValue({status:"connected",last_success_at:"2026-09-10T10:00:00Z"});});
it("loads owner integration state into both shell variants",async()=>{const layout=await Layout({children:"Contenu"});await act(async()=>{render(layout);});expect(m.getQontoIntegration).toHaveBeenCalledWith({},"owner");expect(screen.getAllByText("Qonto : données synchronisées")).toHaveLength(2);});
it("guards reads before shell loading",async()=>{m.requireOwner.mockRejectedValue(new Error("redirect"));await expect(Layout({children:null})).rejects.toThrow("redirect");expect(m.createClient).not.toHaveBeenCalled();});
